### ISSUE TITLE
Make code more robust so that it can deal with old datasets that don't have any annotations

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-lookup-server-annotation-filter-plugin#1]
Traceback:

```
[2021-02-12 18:25:10,875] ERROR in app: Exception on /annotation_filter_plugin/annotation_keys [POST]
Traceback (most recent call last):
  File "/home/dtool/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dtool/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dtool/venv/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/dtool/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dtool/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dtool/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dtool/venv/lib/python2.7/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/home/dtool/venv/lib/python2.7/site-packages/dtool_lookup_server_annotation_filter_plugin/__init__.py", line 57, in annotation_keys
    data = get_annotation_key_info_by_user(username, query)
  File "/home/dtool/venv/lib/python2.7/site-packages/dtool_lookup_server_annotation_filter_plugin/utils.py", line 113, in get_annotation_key_info_by_user
    if _exclude_dataset_info_filter(ds, filters):
  File "/home/dtool/venv/lib/python2.7/site-packages/dtool_lookup_server_annotation_filter_plugin/utils.py", line 53, in _exclude_dataset_info_filter
    ds_valid_keys = _extract_valid_keys(ds_info)
  File "/home/dtool/venv/lib/python2.7/site-packages/dtool_lookup_server_annotation_filter_plugin/utils.py", line 33, in _extract_valid_keys
    for key, value in ds_info["annotations"].items():
KeyError: 'annotations'
```

**Comment by tjelvar-olsson** [comment]
Fixed in 18207c6
